name: CMake

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
        matrix:
            os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - uses: actions/upload-artifact@v2
      with:
        name: CMakeActionsTest-ubuntu
        path: build/CMakeActionsTest

    - name: Echo
      run: echo "Completed on feature branch!"
