name: CMake

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build
