name: CMake

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - uses: actions/upload-artifact@v2
      with:
        path: build/CMakeActionsTest

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        path: build/Debug/CMakeActionsTest.exe
